#!/bin/sh

# THIS A TEMPLATE FOR POSTINST DKMS SCRIPTS

post_install() {

set -e

DKMS_NAME=nvidia
DKMS_VERSION=545.29.06

dkms add -m ${DKMS_NAME} -v ${DKMS_VERSION}
dkms build -m ${DKMS_NAME} -v ${DKMS_VERSION} && dkms install -m ${DKMS_NAME} -v ${DKMS_VERSION} --force || true

post_upgrade

}
