#!/bin/sh
set -e
# Automatically added by dh_dkms/3.0.10-8+deb12u1
DKMS_NAME=nvidia-current
DKMS_VERSION=525.147.05

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
